apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-proxy-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: {{ .Values.kong.ingress.ingressClass }}
spec:
  rules:
    - host: {{ .Values.kong.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway-kong-proxy
                port:
                  number: 80
