services:

  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - minio-volume:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: miniorootpassword
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - internal

  postgres-auth-service:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-auth-service-volume:/var/lib/postgresql/data
    networks:
      - internal

  static-service:
    build:
      context: ./static-service
    restart: unless-stopped
    depends_on:
      - otel-collector
    environment:
      PORT: 80
      APP_ENV: local
      OTLP_DOMAIN: otel-collector:4317
      S3_ACCESS_KEY: root
      S3_SECRET_KEY: miniorootpassword
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET_PROFILE_PICTURES: profile-pictures
    networks:
      - internal

  auth-service:
    build:
      context: ./auth-service
    restart: unless-stopped
    depends_on:
      - postgres-auth-service
      - otel-collector
    environment:
      HTTP_PORT: 80
      GRPC_PORT: 443
      APP_ENV: local
      DB_HOST: postgres-auth-service
      DB_PORT: 5432
      DB_DATABASE: auth_service
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_SCHEMA: public
      OTLP_DOMAIN: otel-collector:4317
      JWT_SECRET: yolelelele
      S3_ACCESS_KEY: root
      S3_SECRET_KEY: miniorootpassword
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET_PROFILE_PICTURES: profile-pictures
      PUBLIC_STATIC_SERVICE_ENDPOINT: http://localhost:8000/static/
    networks:
      - internal

  postgres-assignment-service:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: assignment_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-assignment-service-volume:/var/lib/postgresql/data

  assignment-service:
    build:
      context: ./assignment-service
    restart: unless-stopped
    depends_on:
      - postgres-assignment-service
      - otel-collector
    environment:
      PORT: 80
      APP_ENV: local
      DB_HOST: postgres-assignment-service
      DB_PORT: 5432
      DB_DATABASE: assignment_service
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_SCHEMA: public
      OTLP_DOMAIN: otel-collector:4317
      JWT_SECRET: yolelelele
      GRPC_MISSION_SERVICE_DOMAIN: mission-service:443
    networks:
      - internal

  postgres-mission-service:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: mission_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - internal
    volumes:
      - postgres-mission-service-volume:/var/lib/postgresql/data

  mission-service:
    build:
      context: ./mission-service
    restart: unless-stopped
    depends_on:
      - postgres-mission-service
      - otel-collector
    environment:
      HTTP_PORT: 80
      GRPC_PORT: 443
      APP_ENV: local
      DB_HOST: postgres-mission-service
      DB_PORT: 5432
      DB_DATABASE: mission_service
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_SCHEMA: public
      OTLP_DOMAIN: otel-collector:4317
      JWT_SECRET: yolelelele
    networks:
      - internal

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./config/otel-collector.yaml:/etc/otel/otel-collector.yaml
    command: ["--config=/etc/otel/otel-collector.yaml"]
    depends_on:
      - cadvisor
    networks:
      - internal

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-volume:/var/lib/grafana
    depends_on:
      - tempo
    networks:
      - internal

  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempo-volume:/var/tempo

  tempo:
    image: *tempoImage
    volumes:
      - tempo-volume:/var/lib/tempo
      - ./config/tempo.yaml:/etc/tempo/tempo.yaml
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    environment:
      - LOG_LEVEL=info
    depends_on:
      - init
    networks:
      - internal

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - internal

  loki:
    restart: unless-stopped
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - internal

  cadvisor:
    restart: unless-stopped
    image: google/cadvisor:latest
    command:
      - --docker_only
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    networks:
      - internal

  kong:
    image: kong:latest
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_PORTAL: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/kong.yaml"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_TRACING_INSTRUMENTATIONS: "all"
      KONG_PLUGINS: "opentelemetry"
      KONG_TRACING: "on"
      KONG_TRACING_SAMPLING_RATE: "1.0"
    volumes:
      - ./config/kong.yaml:/kong/kong.yaml
    ports:
      - 8000:8000
    networks:
      - internal

volumes:
  postgres-auth-service-volume:
  postgres-assignment-service-volume:
  postgres-mission-service-volume:
  grafana-volume:
  minio-volume:
  tempo-volume:
  prometheus-volume:
  loki-volume:

networks:
  internal:
    driver: bridge