apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  destination:
    name: ""
    namespace: minio
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://charts.min.io
    targetRevision: 5.3.0
    chart: minio
    helm:
      parameters:
        - name: rootUser
          value: root
        - name: rootPassword
          value: miniorootpassword
        - name: replicas
          value: "2"
        - name: persistence.size
          value: 10Gi
        - name: resources.requests.memory
          value: 1Gi
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
