receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: "cadvisor"
          scrape_interval: 10s
          static_configs:
            - targets: ["0.0.0.0:8181"]
    target_allocator:
      endpoint: http://cadvisor:8080
      interval: 10s
      collector_id: "otel-collector"

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_mib: 500
    spike_limit_mib: 200
    limit_percentage: 80

exporters:
  # zipkin:
  #   endpoint: http://jaeger:9411/api/v2/spans
  #   tls:
  #     insecure: true
  prometheus:
    endpoint: 0.0.0.0:8181
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  otlphttp:
    endpoint: http://loki:3100/otlp

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      # exporters: [zipkin]
      exporters: [otlp]

    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, memory_limiter]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [otlphttp]

  telemetry:
    metrics:
      level: basic
    logs:
      level: info
