FROM golang:1.22.2-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o assignment-service ./cmd

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/assignment-service .
COPY --from=builder /app/migrations ./migrations

EXPOSE 80

CMD ["./assignment-service"]
