apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      containerPort: {{ .Values.service.http.port }}
      protocol: TCP
    - name: grpc
      containerPort: {{ .Values.service.grpc.port }}
      protocol: TCP
  selector:
    {{- include "auth-service.selectorLabels" . | nindent 4 }}
