FROM golang:1.23.2-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o static-service ./cmd

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/static-service .

EXPOSE 80

CMD ["./static-service"]
