CREATE TABLE owned_themes (
    id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL,
    theme_id INTEGER REFERENCES themes (id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);