//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Assignments struct {
	ID          int32 `sql:"primary_key"`
	UserID      uuid.UUID
	Title       string
	Note        *string
	DueDate     *time.Time
	IsCompleted *bool
	IsImportant *bool
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}
