apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    name: ""
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 66.2.1
    chart: kube-prometheus-stack
    helm:
      parameters:
        - name: grafana.persistence.enabled
          value: "true"
        - name: grafana.persistence.size
          value: "2Gi"
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
